language: ñ

env:
  global:
    - LUAROCKS_VER=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

before_install:
  - bash .travis/setup_lua.sh
  - sudo pip install cpp-coveralls

install:
  - sudo luarocks make rockspec/lua-cmsgpack-scm-1.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script:
  - lua test.lua

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
