language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.2.0
  matrix:
    - LUA=lua5.1    LUA_SFX=
    - LUA=lua5.2    LUA_SFX=
    - LUA=lua5.3    LUA_SFX=
    - LUA=luajit    LUA_SFX=jit
    - LUA=luajit2.1 LUA_SFX=jit

before_install:
  - bash -x .travis/setup_lua.sh
  - sudo pip install cpp-coveralls

install:
  - sudo luarocks make rockspec/lua-cmsgpack-scm-1.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script:
  - lua$LUA_SFX test.lua

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always
